### ISSUE TITLE
create dng_tags config

### ISSUE THREAD

**Issue by mkutu** [precision-sustainable-ag/SemiF-Preprocessing#28]
create dng_tags config to hold all the config values for the dng tags

`conf/dng_tags/default.yaml`

```yaml
defaults:
  - _self_
  - paths: default
  - dng_tags: default
  - override hydra/job_logging: custom
```

implement in config values in Matt's `dng2jpg.py` in `feature/pipeline` script
